### ISSUE TITLE
Reproducible Code based on data type

### ISSUE THREAD

**Issue by pburnsdata** [SafetyGraphics/safetyGraphics#159]
Change the code that's provided in the info tab based on whether the file is sas7bdat or csv

See Beccas comment on [157](https://github.com/ASA-DIA-InteractiveSafetyGraphics/safetyGraphics/pull/157)

**Comment by bzkrouse** [comment]
Consider using rio::import() to load data, as it generalizes to either file type.

**Comment by jwildfire** [comment]
With 2.0 we're moving away from data import in the main app (instead data should be passed to the safetyGraphicsApp() function call). We can consider adding a module/app/plugin that helps users load their data and initialize the app later though. Either way, closing this for now. Expectation for now in the exports code will be that the user provides a data.frame.
