### ISSUE TITLE
Handle non required spec variables in Detect standard

### ISSUE THREAD

**Issue by pburnsdata** [SafetyGraphics/safetyGraphics#163]
Currently, detectstandard only checks required variables and passes along information on them. However, some standard variables, like visit and visit number are not required. If we wanted to populate these in generate settings we would need to pass information from detectstandard on the presence or absence of these variables.

**Comment by jwildfire** [comment]
`generateStandard` will also need updates - right now only required settings are added for a given data standard. 

Had an early version implemented [here](https://github.com/ASA-DIA-InteractiveSafetyGraphics/safetyGraphics/commit/ccc6baa94e1a757f50251a8dcad94ee2a09bd379), but took it out for the time being.

**Comment by jwildfire** [comment]
@pburnsdata I'm 90% sure this is no longer relevant after the recent refactor(s)

Closing, but feel free to re-open with more details if there's something we need to do here.
