### ISSUE TITLE
Can't generate export file behind firewall

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#187]
Error looks like this:
![screen shot 2019-02-21 at 12 06 19 pm](https://user-images.githubusercontent.com/3680095/53218733-26379980-3612-11e9-8728-b93ec1c1323a.png)

Would be nice to implement a workaround

**Comment by jwildfire** [comment]
Issue is with attempt to import open sans import at the top of  `webcharts.css` that fails (I assume) because the user's firewall has blocked `fonts/googleapis.com`. 

Honestly, it'd be fine to just remove the import in webcharts and use the fallback if the user doesn't already have it installed, but that would require a change to webcharts (or a hack-y edit to webcharts css in this library). Would be nice if there was a way to tell pandoc to carry on without the import, but not sure if that is possible ... 

@pburnsdata @bzkrouse any bright ideas?

**Comment by jwildfire** [comment]
Per this [thread](https://stackoverflow.com/questions/41284863/pandoc-document-conversion-failed-with-error-67). Maybe we can add a way to make an export that isn't self contained ...

**Comment by pburnsdata** [comment]
@jwildfire Yeah what you're saying makes sense. I've been playing with this some (recreating by unplugging by ethernet cable :P)

There is a pandoc setting for ignoring warnings but not for errors and this looks like an error. I'm guessing that it's not going to proceed if it can't find one of the resource it's supposed to have, so my hunch is we won't be able to find an easy way for it to carry on without the import.

Alternatively, if we tried to provide the dependencies locally (I think that's what setting self-contained to false would mean) we'd be doing one of the solutions you mentioned in the comment above (e.g. editing the webcharts css to import a local version of the google css file -which has a lot of url requests itself....)

**Comment by jwildfire** [comment]
As discussed, this requires an update in webcharts. [Issue](https://github.com/RhoInc/Webcharts/issues/238) filed.

@zskrivan is having the same problem, so need to bump up priority a bit.  Going to pencil this in to v0.10.0
