### ISSUE TITLE
Dynamically-created settings object

### ISSUE THREAD

**Issue by bzkrouse** [SafetyGraphics/safetyGraphics#193]
Settings and validation objects become lists of lists - where each nested list represents a different chart type.  Setting object is dynamically generated based on settings object metadata refactor

**Comment by jwildfire** [comment]
Per the comment in #168, I don't think we should tackle a full refactor of the settings/validation workflow right now. 

Don't think it should be tooooo painful to update the Shiny module with the current structure ...

**Comment by jwildfire** [comment]
This is at least partially covered in #199 ... will re-evaluate once we've made some progress there.

**Comment by bzkrouse** [comment]
Code snippet to grab all Shiny input values: 

```
 input_names <- reactive({safetyGraphics:::getSettingsMetadata(charts=input$selected_charts, cols="text_key")})

  observe({
    req(input_names())
    keys <- input_names()
    inputValues <- list()
    for (key in keys){
      if (is.null(input[[key]])){
        inputValues[key] <- list(input[[key]])
      } else {
        inputValues[[key]] <- input[[key]]
      }
    }
    print(inputValues)
  })
```

**Comment by jwildfire** [comment]
@bzkrouse Still buggy, but [this](https://github.com/SafetyGraphics/safetyGraphics/commit/3bd6d85f8a500acacd6bfb8c285ea7c04ad09373) is the general framework I had in mind.
