### ISSUE TITLE
 Make generic rendererChart() function

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#217]
Take any compatible htmlWidget and render the chart.

**Comment by bzkrouse** [comment]
We aren't too far off, but worthwhile to make sure our widget function names and shiny binding functions have standard names (e.g. same capitalization, same prefix) so we can call them dynamically based on the "charts" that get passed to renderChart().

**Comment by jwildfire** [comment]
Requirement for htmlwidgets:
- name of widget should be lowercase
- widget renderer should be called `render_{widgetname}`
