### ISSUE TITLE
Clearing a setting in the Settings UI invalidates that setting

### ISSUE THREAD

**Issue by pburnsdata** [SafetyGraphics/safetyGraphics#223]
Example: If you choose a variable for baseline value col and then change your mind and delete it, a red x will appear and you will not be able to get valid settings again without specifying a baseline value col. Users should be able to remove optional settings I'd imagine

**Comment by bzkrouse** [comment]
Same as #192 ?

**Comment by jwildfire** [comment]
Seems to be ok with the updates. Can you please confirm and close if you can't recreate the bug, @pburnsdata?

**Comment by pburnsdata** [comment]
Deleting a setting still seems to be a problem inc ertain circumstances. For example, backspace the measure column default setting - the app should crash.
