### ISSUE TITLE
User settings are removed when chart-type changes

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#232]
All changes the user has made on the settings page are removed when a chart is toggled, and defaults based on the data are shown.

**Comment by bzkrouse** [comment]
possible solution per conversation w/ @pburnsdata:

1) need to wrap input$charts in isolate() for create settings UI
2) add observer that listens to input$charts and does the following:

```
  observeEvent(input$charts,{
    # 1. filter settings metadata to relevant inputs
    # 2. identify which settings in input_names() are not relevant
    # 3. use shinyJS::hide() to hide these inputs (loop thru)
  })
```
