### ISSUE TITLE
Warning in console after installing package from GitHub

### ISSUE THREAD

**Issue by bzkrouse** [SafetyGraphics/safetyGraphics#284]
In some instances, the following warning appears after ```install_github("SafetyGraphics/safetyGraphics)```:  

![image](https://user-images.githubusercontent.com/14199771/57301734-b0d35500-70a7-11e9-83a8-68c83322e4ab.png)

**Comment by jwildfire** [comment]
Seems ok on mac with latest release ... maybe windows specific?

**Comment by bzkrouse** [comment]
This seems to have resolved for me after updating my R/RStudio/Rtools...
