### ISSUE TITLE
create Vignette about custom charts

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#309]
- Sending custom settings to the renderChart widget
- Setting up your own chart

**Comment by jwildfire** [comment]
linked to #310

**Comment by bzkrouse** [comment]
![image](https://user-images.githubusercontent.com/14199771/67016263-eacc6c80-f0c5-11e9-9f03-9cc1f12a5a1d.png)

**Comment by bzkrouse** [comment]
![image](https://user-images.githubusercontent.com/14199771/67016434-2ff09e80-f0c6-11e9-892b-94e57438ca9a.png)

**Comment by jwildfire** [comment]
![image](https://user-images.githubusercontent.com/3680095/67284859-ca792500-f4ac-11e9-9c70-fc0565447b7b.png)

**Comment by bzkrouse** [comment]
Jotting down thoughts on adding a custom htmlwidget: 
- Need another column of metadata that distinguishes the included widgets (which are built within safetyGraphics using createWidget()) vs. custom widgets (which are presumably sourced from another package)
- Based on this metadata, ```chartRenderer()``` will conditionally build the widget or source the widget function
- customSettings.R will source the widget as such:  ```customWidget <- pkgname::widgetfun()```

**Comment by jwildfire** [comment]
Good summary, that all makes sense to me. I agree that we should just require that custom renderers be hosted in another package for now. 

Going to send the current wiki out for review shortly, with a coming soon for html widgets. Let's see how hard it is to get an custom htmlwidget example running in a branch (maybe using the new delta-delta renderer?), and then decide whether to include in v1.1 or bump to a later release.
