### ISSUE TITLE
Framework for updating existing settings object in app

### ISSUE THREAD

**Issue by bzkrouse** [SafetyGraphics/safetyGraphics#336]
This would require a refactor for how we create and modify settings objects.  Current workflow for updating a settings object (e.g. when user changes an app setting) involves re-generating entire settings object.

Consider moving towards storing settings in reactiveValues() list.  Can store settings in conjunction w/ uploaded dataset.

Related issues: #334, #324, #168, #73

**Comment by jwildfire** [comment]
Settings framework changing enough in v2 that the details here likely aren't relevant. Can file a new issue to capture this kind of functionality if desired.
