### ISSUE TITLE
Simplify metadata storage and workflow

### ISSUE THREAD

**Issue by bzkrouse** [SafetyGraphics/safetyGraphics#338]
Is it possible to simplify any of the following:
- Editing multiple metadata files for addition of new chart
- Hierarchy of settings object values (e.g. measure_col vs. measure_values--ALT)

**Comment by bzkrouse** [comment]
Currently we have:
- 3 metadata files (2 .csv, 1 .R) that are 1 row per setting
- 2 metadata files that are 1 column/row per chart

Consider grouping together files of similar structure.

**Comment by jwildfire** [comment]
With the process introduced in v1.1, I think I'm ok with our current workflow (regarding the metadata at least). Going to close this for now, but feel free to re-open with more notes if you've got ideas for improvements. 

#396 is somewhat related, btw.
