### ISSUE TITLE
Consider adding "upload settings" button

### ISSUE THREAD

**Issue by pburnsdata** [SafetyGraphics/safetyGraphics#360]
Consider adding an "upload settings" button into the app for a user-friendly option per Becca in https://github.com/SafetyGraphics/safetyGraphics/pull/347

**Comment by jwildfire** [comment]
@pburnsdata @bzkrouse Still something we want to consider? How would this work? 

Let's add some more detail here or close this out as won't fix.

**Comment by jwildfire** [comment]
Still not sure about the exact workflow here ... Going to mark as wontfix and close out after v2 unless someone wants to provide more details.

**Comment by jwildfire** [comment]
Users can pass in a custom mapping in v2.0. Will allow upload if/when we make the app to help with set-up.
