### ISSUE TITLE
Bug in maxWidth for addChart()

### ISSUE THREAD

**Issue by bzkrouse** [SafetyGraphics/safetyGraphics#367]
Doesn't seem to be working for type="static"

**Comment by jwildfire** [comment]
Leaving this for now, but we will need to revisit in v2.0 to see if this is still relevant.

**Comment by jwildfire** [comment]
Putting in 2.0 for now, though still not sure if this is needed. Re-evaluate before release.

**Comment by jwildfire** [comment]
Closing since this is unlikely to work this way in v2.
