### ISSUE TITLE
App crashing when working directory does not contain settings files

### ISSUE THREAD

**Issue by pburnsdata** [SafetyGraphics/safetyGraphics#383]
This is related to code in safetyGraphicsApp() and global.R.

safetyGraphicsApp()
![509_171_1](https://user-images.githubusercontent.com/26064686/70631332-0736e200-1bfb-11ea-8575-a6b1ac2960db.png)

global.R in shiny app:
![537_107_1](https://user-images.githubusercontent.com/26064686/70631311-01d99780-1bfb-11ea-950f-28566bc30f52.png)

In safetyGraphicsApp(), settings_location is currently being set to the value of getwd() and since it's never not NULL, the app is always looking for user metadata. When that user metadata doesn't exist the app crashes. 

We could fix this by setting the sg_***metadata_dfs to the default settings metadata files when they aren't found in the working directory. However, it might be worth considering if we should be using the current working directory as the default location? What are the pros and cons to that? If users have to set their working directory to the location of their files in a previous step for safetyGraphicsApp() to find them, why not just set them within the function with settingsLocation like we did before and have a single workflow for telling the app where to find settings files?

**Comment by jwildfire** [comment]
Going to change default for settingsLocation to `"."` and then rework the logic to give priority to user specified locations over the working directory. Tests:

```
safetyGraphicsApp(settingsLocation=".")
safetyGraphicsApp(settingsLocation=NULL)
safetyGraphicsApp(settingsLocation="/path/with/no/file")
safetyGraphicsApp(settingsLocation="/valid/path")
```
