### ISSUE TITLE
Sort values in data mapping dropdowns alphabetically.

### ISSUE THREAD

**Issue by samussiah** [SafetyGraphics/safetyGraphics#416]
specifically value mappings, not variable mappings

**Comment by jwildfire** [comment]
Good idea. Should be fairly easy to implement in v2.0 or as a later tweak.

**Comment by jwildfire** [comment]
cc: @bzkrouse

**Comment by jwildfire** [comment]
Actually not sure this makes sense in retrospect. Can re-open if more users request in the future
