### ISSUE TITLE
Variable value dropdowns don't populate when loading datasets via the loadData option.

### ISSUE THREAD

**Issue by samussiah** [SafetyGraphics/safetyGraphics#417]
Steps to reproduce:

1. Load a dataset: `lb <- data.table::fread('https://raw.githubusercontent.com/RhoInc/data-library/master/data/clinical-trials/sdtm/lb.csv', sep = ',', na.strings = NULL, colClasses = 'character')`.
2. Launch safetyGraphicsApp: `safetyGraphicsApp(loadData = TRUE)`.
3. Navigate to the data tab and select _lb_.
4. Navigate to the Settings tab and select _LBTEST_ as the _Measure column_.
5. Value dropdowns only display the associated variable name.

![image](https://user-images.githubusercontent.com/5428548/78595390-edf41a00-7817-11ea-9ceb-cb0f09aea038.png)

**Comment by jwildfire** [comment]
That is a weird bug ... Not sure what is going on ... 

At any rate, the data mapping process is being fully re-written for v2.0, so marking this as won't fix and closing.
