### ISSUE TITLE
Update standardsMetadata to accept domain-prefixed columns.

### ISSUE THREAD

**Issue by samussiah** [SafetyGraphics/safetyGraphics#418]
e.g. LBTEST and VSTEST in addition to TEST, LBSTRESN in addition to STRESN, etc.

**Comment by jwildfire** [comment]
Not sure if we should handle this with multiple data standards, or if it would be better to make the existing data standards more flexible (ie - allowing multiple column names for a given parameter). Worth considering after v2.0 release.

**Comment by jwildfire** [comment]
Plan in 2.0 is to have users to mapping once, then save for reuse. Certainly possible to add additional standards to the default metadata, but probably not high priority with the new workflow, so going to close the issue until it becomes a recurring request.
