### ISSUE TITLE
Replace curved quotes with regular quotes in the Custom Workflows vignette.

### ISSUE THREAD

**Issue by samussiah** [SafetyGraphics/safetyGraphics#419]

**Comment by jwildfire** [comment]
Vingettes are going to need a major re-write with v2.0, but leaving this issue active jut to make sure we double check before release.

**Comment by jwildfire** [comment]
Labeling as invalid, but leaving open. Will close after final check before v2.0 release.

**Comment by jwildfire** [comment]
Not an issue in new vignette.
