### ISSUE TITLE
Update charting vignette with safetyGraphics/safetyCharts primary usage

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#445]
Describe the differences between safetyGraphics and safetyCharts near the beginning of the package.

**Comment by jwildfire** [comment]
@xni7 I added [this section](https://github.com/SafetyGraphics/safetyGraphics/wiki/Chart-Configuration-Vignette-(v2)#introducing-the-safetycharts-r-package) in the wiki. 

Let me know what you think? Any updates?

**Comment by xni7** [comment]
@jwildfire , would we call {safetyCharts} a dependency for {safetyGraphics}? I feel so, and I attempted to add it in the [DESCRIPTION](https://github.com/SafetyGraphics/safetyGraphics/blob/module-renderer-renv/DESCRIPTION) of the renv branch. There is an article [devtools dependencies](https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html) that suggest putting the Github source in the Remotes field.

**Comment by jwildfire** [comment]
> would we call {safetyCharts} a dependency for {safetyGraphics}?

Yes - filed an issue to deal with this soon. Closing this issue since wiki work is done.
