### ISSUE TITLE
Implement {renv}

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#446]

**Comment by xni7** [comment]
Pushed a new branch [module-renderer-renv](https://github.com/SafetyGraphics/safetyGraphics/tree/module-renderer-renv) with renv environment. It was branched off the module-renderer branch.

The [renv.lock](https://github.com/SafetyGraphics/safetyGraphics/blob/module-renderer-renv/renv.lock) json file shows 165 R package dependencies. You can use `renv::restore()` to restore the environment. I set `safetyCharts` as a dependency for `safetyGraphics` in the [DESCRIPTION](https://github.com/SafetyGraphics/safetyGraphics/blob/module-renderer-renv/DESCRIPTION) file.

I also had to hard code `app_ui.R` app_css line to make it work. 

No | Package | Version | Source | Repository | Hash | RemoteType | RemoteHost | RemoteUsername | RemoteRepo | RemoteRef | RemoteSha
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | BH | 1.72.0-3 | Repository | CRAN | 8f9ce74c6417d61f0782cbae5fd2b7b0 | NA | NA | NA | NA | NA | NA
2 | DBI | 1.1.0 | Repository | CRAN | 4744be45519d675af66c28478720fce5 | NA | NA | NA | NA | NA | NA
3 | DT | 0.16 | Repository | CRAN | acac794cc3e393ca65f916e5ced5c1d2 | NA | NA | NA | NA | NA | NA
4 | KernSmooth | 2.23-17 | Repository | CRAN | bbff70c8c0357b5b88238c83f680fcd3 | NA | NA | NA | NA | NA | NA
5 | MASS | 7.3-53 | Repository | CRAN | d1bc1c8e9c0ace57ec9ffea01021d45f | NA | NA | NA | NA | NA | NA
6 | Matrix | 1.2-18 | Repository | CRAN | 08588806cba69f04797dab50627428ed | NA | NA | NA | NA | NA | NA
7 | R6 | 2.5.0 | Repository | CRAN | b203113193e70978a696b2809525649d | NA | NA | NA | NA | NA | NA
8 | RColorBrewer | 1.1-2 | Repository | CRAN | e031418365a7f7a766181ab5a41a5716 | NA | NA | NA | NA | NA | NA
9 | Rcpp | 1.0.5 | Repository | CRAN | 125dc7a0ed375eb68c0ce533b48d291f | NA | NA | NA | NA | NA | NA
10 | Tendril | 2.0.4 | Repository | CRAN | 790bed9b459fa3bdd36ce85fb2a9ba23 | NA | NA | NA | NA | NA | NA
11 | Tplyr | 0.2.1 | Repository | CRAN | 46085bce505db24bafaa901d794933f3 | NA | NA | NA | NA | NA | NA
12 | askpass | 1.1 | Repository | CRAN | e8a22846fff485f0be3770c2da758713 | NA | NA | NA | NA | NA | NA
13 | assertthat | 0.2.1 | Repository | CRAN | 50c838a310445e954bc13f26f26a6ecf | NA | NA | NA | NA | NA | NA
14 | backports | 1.2.0 | Repository | CRAN | fb0efa7042b45dac543dd3995a6dac0b | NA | NA | NA | NA | NA | NA
15 | base64enc | 0.1-3 | Repository | CRAN | 543776ae6848fde2f48ff3816d0628bc | NA | NA | NA | NA | NA | NA
16 | blob | 1.2.1 | Repository | CRAN | 9addc7e2c5954eca5719928131fed98c | NA | NA | NA | NA | NA | NA
17 | boot | 1.3-25 | Repository | CRAN | bd51734a754b6c2baf28b2d1ebc11e91 | NA | NA | NA | NA | NA | NA
18 | brew | 1.0-6 | Repository | CRAN | 92a5f887f9ae3035ac7afde22ba73ee9 | NA | NA | NA | NA | NA | NA
19 | brio | 1.1.0 | Repository | CRAN | 570a24963009b9cce0869a0463c83580 | NA | NA | NA | NA | NA | NA
20 | broom | 0.7.2 | Repository | CRAN | b00000a87b8a4a1e8a8fc413c1dbad03 | NA | NA | NA | NA | NA | NA
21 | callr | 3.5.1 | Repository | CRAN | b7d7f1e926dfcd57c74ce93f5c048e80 | NA | NA | NA | NA | NA | NA
22 | cellranger | 1.1.0 | Repository | CRAN | f61dbaec772ccd2e17705c1e872e9e7c | NA | NA | NA | NA | NA | NA
23 | class | 7.3-17 | Repository | CRAN | 9267f5dab59a4ef44229858a142bded1 | NA | NA | NA | NA | NA | NA
24 | cli | 2.2.0 | Repository | CRAN | 3ef298932294b775fa0a3eeaa3a645b0 | NA | NA | NA | NA | NA | NA
25 | clipr | 0.7.1 | Repository | CRAN | ebaa97ac99cc2daf04e77eecc7b781d7 | NA | NA | NA | NA | NA | NA
26 | clisymbols | 1.2.0 | Repository | CRAN | 96c01552bfd5661b9bbdefbc762f4bcd | NA | NA | NA | NA | NA | NA
27 | cluster | 2.1.0 | Repository | CRAN | db63a44aab5aadcb6bf2f129751d129a | NA | NA | NA | NA | NA | NA
28 | codetools | 0.2-16 | Repository | CRAN | 89cf4b8207269ccf82fbeb6473fd662b | NA | NA | NA | NA | NA | NA
29 | colorspace | 2.0-0 | Repository | CRAN | abea3384649ef37f60ef51ce002f3547 | NA | NA | NA | NA | NA | NA
30 | commonmark | 1.7 | Repository | CRAN | 0f22be39ec1d141fd03683c06f3a6e67 | NA | NA | NA | NA | NA | NA
31 | covr | 3.5.1 | Repository | CRAN | 6d80a9fc3c0c8473153b54fa54719dfd | NA | NA | NA | NA | NA | NA
32 | cpp11 | 0.2.4 | Repository | CRAN | ba66e5a750d39067d888aa7af797fed2 | NA | NA | NA | NA | NA | NA
33 | crayon | 1.3.4 | Repository | CRAN | 0d57bc8e27b7ba9e45dba825ebc0de6b | NA | NA | NA | NA | NA | NA
34 | crosstalk | 1.1.0.1 | Repository | CRAN | ae55f5d7c02f0ab43c58dd050694f2b4 | NA | NA | NA | NA | NA | NA
35 | curl | 4.3 | Repository | CRAN | 2b7d10581cc730804e9ed178c8374bd6 | NA | NA | NA | NA | NA | NA
36 | data.table | 1.13.2 | Repository | CRAN | 907b184e0fd13bc19154a8f322920015 | NA | NA | NA | NA | NA | NA
37 | dbplyr | 2.0.0 | Repository | CRAN | 714005206038b1dda74cb1de85029a20 | NA | NA | NA | NA | NA | NA
38 | debugme | 1.1.0 | Repository | CRAN | 2d8a9e4f08f3dd669cb8ddd1eb575959 | NA | NA | NA | NA | NA | NA
39 | desc | 1.2.0 | Repository | CRAN | 6c8fe8fa26a23b79949375d372c7b395 | NA | NA | NA | NA | NA | NA
40 | devtools | 2.3.2 | Repository | CRAN | 415656f50722f5b6e6bcf80855ce11b9 | NA | NA | NA | NA | NA | NA
41 | diffobj | 0.3.2 | Repository | CRAN | 16533929cf545f3c9b796780cccf5eff | NA | NA | NA | NA | NA | NA
42 | digest | 0.6.27 | Repository | CRAN | a0cbe758a531d054b537d16dff4d58a1 | NA | NA | NA | NA | NA | NA
43 | downlit | 0.2.1 | Repository | CRAN | f24f1e44320a978c03050b8403a83793 | NA | NA | NA | NA | NA | NA
44 | dplyr | 1.0.2 | Repository | CRAN | d0509913b27ea898189ee664b6030dc2 | NA | NA | NA | NA | NA | NA
45 | ellipsis | 0.3.1 | Repository | CRAN | fd2844b3a43ae2d27e70ece2df1b4e2a | NA | NA | NA | NA | NA | NA
46 | esquisse | 0.3.1 | Repository | CRAN | ad07068d91410eee1690c3f6b90a2f24 | NA | NA | NA | NA | NA | NA
47 | evaluate | 0.14 | Repository | CRAN | ec8ca05cffcc70569eaaad8469d2a3a7 | NA | NA | NA | NA | NA | NA
48 | fansi | 0.4.1 | Repository | CRAN | 7fce217eaaf8016e72065e85c73027b5 | NA | NA | NA | NA | NA | NA
49 | farver | 2.0.3 | Repository | CRAN | dad6793a5a1f73c8e91f1a1e3e834b05 | NA | NA | NA | NA | NA | NA
50 | fastmap | 1.0.1 | Repository | CRAN | 83ab58a0518afe3d17e41da01af13b60 | NA | NA | NA | NA | NA | NA
51 | forcats | 0.5.0 | Repository | CRAN | 1cb4279e697650f0bd78cd3601ee7576 | NA | NA | NA | NA | NA | NA
52 | foreign | 0.8-80 | Repository | CRAN | ae1b1e15cc6ccb2bc61c0ac33e86d35f | NA | NA | NA | NA | NA | NA
53 | fs | 1.5.0 | Repository | CRAN | 44594a07a42e5f91fac9f93fda6d0109 | NA | NA | NA | NA | NA | NA
54 | generics | 0.1.0 | Repository | CRAN | 4d243a9c10b00589889fe32314ffd902 | NA | NA | NA | NA | NA | NA
55 | ggplot2 | 3.3.2 | Repository | CRAN | 4ded8b439797f7b1693bd3d238d0106b | NA | NA | NA | NA | NA | NA
56 | gh | 1.1.0 | Repository | CRAN | 89ea5998938d1ad55f035c8a86f96b74 | NA | NA | NA | NA | NA | NA
57 | git2r | 0.27.1 | Repository | CRAN | 531a82d1beed1f545beb25f4f5945bf7 | NA | NA | NA | NA | NA | NA
58 | glue | 1.4.2 | Repository | CRAN | 6efd734b14c6471cfe443345f3e35e29 | NA | NA | NA | NA | NA | NA
59 | gtable | 0.3.0 | Repository | CRAN | ac5c6baf7822ce8732b343f14c072c4d | NA | NA | NA | NA | NA | NA
60 | haven | 2.3.1 | Repository | CRAN | 221d0ad75dfa03ebf17b1a4cc5c31dfc | NA | NA | NA | NA | NA | NA
61 | hexbin | 1.28.1 | Repository | CRAN | 3d59212f2814d65dff517e6899813c58 | NA | NA | NA | NA | NA | NA
62 | highr | 0.8 | Repository | CRAN | 4dc5bb88961e347a0f4d8aad597cbfac | NA | NA | NA | NA | NA | NA
63 | hms | 0.5.3 | Repository | CRAN | 726671f634529d470545f9fd1a9d1869 | NA | NA | NA | NA | NA | NA
64 | htmltools | 0.5.0 | Repository | CRAN | 7d651b7131794fe007b1ad6f21aaa401 | NA | NA | NA | NA | NA | NA
65 | htmlwidgets | 1.5.2 | Repository | CRAN | 0aaf56b7960bb066646e1868cadcaf07 | NA | NA | NA | NA | NA | NA
66 | httpuv | 1.5.4 | Repository | CRAN | 4e6dabb220b006ccdc3b3b5ff993b205 | NA | NA | NA | NA | NA | NA
67 | httr | 1.4.2 | Repository | CRAN | a525aba14184fec243f9eaec62fbed43 | NA | NA | NA | NA | NA | NA
68 | ini | 0.3.1 | Repository | CRAN | 6154ec2223172bce8162d4153cda21f7 | NA | NA | NA | NA | NA | NA
69 | isoband | 0.2.2 | Repository | CRAN | 6e58bd3d6b3dd82a944cd6f05ade228f | NA | NA | NA | NA | NA | NA
70 | jsonlite | 1.7.1 | Repository | CRAN | 1ec84e070b88b37ed169f19def40d47c | NA | NA | NA | NA | NA | NA
71 | kableExtra | 1.3.1 | Repository | CRAN | fa7f610e7eadfc9c47d501a333e03f1a | NA | NA | NA | NA | NA | NA
72 | knitr | 1.3 | Repository | CRAN | eed7ee0d02eee88d53881cdc92457c62 | NA | NA | NA | NA | NA | NA
73 | labeling | 0.4.2 | Repository | CRAN | 3d5108641f47470611a32d0bdf357a72 | NA | NA | NA | NA | NA | NA
74 | later | 1.1.0.1 | Repository | CRAN | d0a62b247165aabf397fded504660d8a | NA | NA | NA | NA | NA | NA
75 | lattice | 0.20-41 | Repository | CRAN | fbd9285028b0263d76d18c95ae51a53d | NA | NA | NA | NA | NA | NA
76 | lazyeval | 0.2.2 | Repository | CRAN | d908914ae53b04d4c0c0fd72ecc35370 | NA | NA | NA | NA | NA | NA
77 | lifecycle | 0.2.0 | Repository | CRAN | 361811f31f71f8a617a9a68bf63f1f42 | NA | NA | NA | NA | NA | NA
78 | lubridate | 1.7.9.2 | Repository | CRAN | 5b5b02f621d39a499def7923a5aee746 | NA | NA | NA | NA | NA | NA
79 | magrittr | 2.0.1 | Repository | CRAN | 41287f1ac7d28a92f0a286ed507928d3 | NA | NA | NA | NA | NA | NA
80 | markdown | 1.1 | Repository | CRAN | 61e4a10781dd00d7d81dd06ca9b94e95 | NA | NA | NA | NA | NA | NA
81 | memoise | 1.1.0 | Repository | CRAN | 58baa74e4603fcfb9a94401c58c8f9b1 | NA | NA | NA | NA | NA | NA
82 | mgcv | 1.8-33 | Repository | CRAN | eb7b6439bc6d812eed2cddba5edc6be3 | NA | NA | NA | NA | NA | NA
83 | mime | 0.9 | Repository | CRAN | e87a35ec73b157552814869f45a63aa3 | NA | NA | NA | NA | NA | NA
84 | miniUI | 0.1.1.1 | Repository | CRAN | fec5f52652d60615fdb3957b3d74324a | NA | NA | NA | NA | NA | NA
85 | modelr | 0.1.8 | Repository | CRAN | 9fd59716311ee82cba83dc2826fc5577 | NA | NA | NA | NA | NA | NA
86 | munsell | 0.5.0 | Repository | CRAN | 6dfe8bf774944bd5595785e3229d8771 | NA | NA | NA | NA | NA | NA
87 | nlme | 3.1-149 | Repository | CRAN | 7c24ab3a1e3afe50388eb2d893aab255 | NA | NA | NA | NA | NA | NA
88 | nnet | 7.3-14 | Repository | CRAN | 0d87e50e11394a7151a28873637d799a | NA | NA | NA | NA | NA | NA
89 | openssl | 1.4.3 | Repository | CRAN | a399e4773075fc2375b71f45fca186c4 | NA | NA | NA | NA | NA | NA
90 | parsedate | 1.2.0 | Repository | CRAN | 9ab1426429ad716b42088a0fd8e909ee | NA | NA | NA | NA | NA | NA
91 | pillar | 1.4.7 | Repository | CRAN | 3b3dd89b2ee115a8b54e93a34cd546b4 | NA | NA | NA | NA | NA | NA
92 | pingr | 2.0.1 | Repository | CRAN | e293e79be42ffd336d938937fd3017fb | NA | NA | NA | NA | NA | NA
93 | pkgbuild | 1.1.0 | Repository | CRAN | 404684bc4e3685007f9720adf13b06c1 | NA | NA | NA | NA | NA | NA
94 | pkgconfig | 2.0.3 | Repository | CRAN | 01f28d4278f15c76cddbea05899c5d6f | NA | NA | NA | NA | NA | NA
95 | pkgdown | 1.6.1 | Repository | CRAN | 8896076540d9e9b556a2ec658c81f916 | NA | NA | NA | NA | NA | NA
96 | pkgload | 1.1.0 | Repository | CRAN | b6b150cd4709e0c0c9b5d51ac4376282 | NA | NA | NA | NA | NA | NA
97 | plotly | 4.9.2.1 | Repository | CRAN | b08edf378e0e38959a6983e3d5902795 | NA | NA | NA | NA | NA | NA
98 | plyr | 1.8.6 | Repository | CRAN | ec0e5ab4e5f851f6ef32cd1d1984957f | NA | NA | NA | NA | NA | NA
99 | png | 0.1-7 | Repository | CRAN | 03b7076c234cb3331288919983326c55 | NA | NA | NA | NA | NA | NA
100 | praise | 1.0.0 | Repository | CRAN | a555924add98c99d2f411e37e7d25e9f | NA | NA | NA | NA | NA | NA
101 | prettyunits | 1.1.1 | Repository | CRAN | 95ef9167b75dde9d2ccc3c7528393e7e | NA | NA | NA | NA | NA | NA
102 | processx | 3.4.4 | Repository | CRAN | 03446ed0b8129916f73676726cb3c48f | NA | NA | NA | NA | NA | NA
103 | progress | 1.2.2 | Repository | CRAN | 14dc9f7a3c91ebb14ec5bb9208a07061 | NA | NA | NA | NA | NA | NA
104 | promises | 1.1.1 | Repository | CRAN | a8730dcbdd19f9047774909f0ec214a4 | NA | NA | NA | NA | NA | NA
105 | ps | 1.4.0 | Repository | CRAN | f5d7d94cc097aa9dade988e3e6715067 | NA | NA | NA | NA | NA | NA
106 | purrr | 0.3.4 | Repository | CRAN | 97def703420c8ab10d8f0e6c72101e02 | NA | NA | NA | NA | NA | NA
107 | ragg | 0.4.0 | Repository | CRAN | 34630c700bb331339a80ddc9c6821e25 | NA | NA | NA | NA | NA | NA
108 | rcmdcheck | 1.3.3 | Repository | CRAN | ed95895886dab6d2a584da45503555da | NA | NA | NA | NA | NA | NA
109 | reactlog | 1.1.0 | Repository | CRAN | 5a30d3b8883107ae07c2137a33c000b2 | NA | NA | NA | NA | NA | NA
110 | readr | 1.4.0 | Repository | CRAN | 2639976851f71f330264a9c9c3d43a61 | NA | NA | NA | NA | NA | NA
111 | readxl | 1.3.1 | Repository | CRAN | 63537c483c2dbec8d9e3183b3735254a | NA | NA | NA | NA | NA | NA
112 | rematch | 1.0.1 | Repository | CRAN | c66b930d20bb6d858cd18e1cebcfae5c | NA | NA | NA | NA | NA | NA
113 | rematch2 | 2.1.2 | Repository | CRAN | 76c9e04c712a05848ae7a23d2f170a40 | NA | NA | NA | NA | NA | NA
114 | remotes | 2.2.0 | Repository | CRAN | 430a0908aee75b1fcba0e62857cab0ce | NA | NA | NA | NA | NA | NA
115 | renv | 0.12.2 | Repository | CRAN | 398cc1ea892e1aade66d1ecbb2874d24 | NA | NA | NA | NA | NA | NA
116 | reprex | 0.3.0 | Repository | CRAN | b06bfb3504cc8a4579fd5567646f745b | NA | NA | NA | NA | NA | NA
117 | reshape2 | 1.4.4 | Repository | CRAN | bb5996d0bd962d214a11140d77589917 | NA | NA | NA | NA | NA | NA
118 | rex | 1.2.0 | Repository | CRAN | 093584b944440c5cd07a696b3c8e0e4c | NA | NA | NA | NA | NA | NA
119 | rlang | 0.4.8 | Repository | CRAN | 843a6af51414bce7f8a8e372f11d6cd0 | NA | NA | NA | NA | NA | NA
120 | rmarkdown | 2.5 | Repository | CRAN | 20a0a94af9e8f7040510447763aab3e9 | NA | NA | NA | NA | NA | NA
121 | roxygen2 | 7.1.1 | Repository | CRAN | fcd94e00cc409b25d07ca50f7bf339f5 | NA | NA | NA | NA | NA | NA
122 | rpart | 4.1-15 | Repository | CRAN | 9787c1fcb680e655d062e7611cadf78e | NA | NA | NA | NA | NA | NA
123 | rprojroot | 2.0.2 | Repository | CRAN | 249d8cd1e74a8f6a26194a91b47f21d1 | NA | NA | NA | NA | NA | NA
124 | rstudioapi | 0.13 | Repository | CRAN | 06c85365a03fdaf699966cc1d3cf53ea | NA | NA | NA | NA | NA | NA
125 | rversions | 2.0.2 | Repository | CRAN | 0ec41191f744d0f5afad8c6f35cc36e4 | NA | NA | NA | NA | NA | NA
126 | rvest | 0.3.6 | Repository | CRAN | a9795ccb2d608330e841998b67156764 | NA | NA | NA | NA | NA | NA
127 | safetyCharts | 0.1.0 | GitHub | NA | 8ed1a70b3515fe512f3cb34aad4f362f | github | api.github.com | SafetyGraphics | safetyCharts | dev | 878158d170a8ac2611fc8f4d798cfea3a15e6cfc
128 | scales | 1.1.1 | Repository | CRAN | 6f76f71042411426ec8df6c54f34e6dd | NA | NA | NA | NA | NA | NA
129 | selectr | 0.4-2 | Repository | CRAN | 3838071b66e0c566d55cc26bd6e27bf4 | NA | NA | NA | NA | NA | NA
130 | sessioninfo | 1.1.1 | Repository | CRAN | 308013098befe37484df72c39cf90d6e | NA | NA | NA | NA | NA | NA
131 | shiny | 1.5.0 | Repository | CRAN | ee4ed72d7a5047d9e73cf922ad66e9c9 | NA | NA | NA | NA | NA | NA
132 | shinyWidgets | 0.5.4 | Repository | CRAN | 2d537ac92c7ad118263cbd797c07f180 | NA | NA | NA | NA | NA | NA
133 | shinybusy | 0.2.2 | Repository | CRAN | c38fc071d4def5e642c8dc34c3a082e4 | NA | NA | NA | NA | NA | NA
134 | shinydashboard | 0.7.1 | Repository | CRAN | 133639dc106955eee4ffb8ec73edac37 | NA | NA | NA | NA | NA | NA
135 | shinyjs | 2.0.0 | Repository | CRAN | 9ddfc91d4280eaa34c2103951538976f | NA | NA | NA | NA | NA | NA
136 | shinytest | 1.4.0 | Repository | CRAN | 9697b1139098fc6a7231a4b893316501 | NA | NA | NA | NA | NA | NA
137 | showimage | 1.0.0 | Repository | CRAN | 841927b226db842d24d9c288c99ed27b | NA | NA | NA | NA | NA | NA
138 | sourcetools | 0.1.7 | Repository | CRAN | 947e4e02a79effa5d512473e10f41797 | NA | NA | NA | NA | NA | NA
139 | spatial | 7.3-12 | Repository | CRAN | 58a02ce0150652b96c044bc67a0df2e5 | NA | NA | NA | NA | NA | NA
140 | stringi | 1.5.3 | Repository | CRAN | a063ebea753c92910a4cca7b18bc1f05 | NA | NA | NA | NA | NA | NA
141 | stringr | 1.4.0 | Repository | CRAN | 0759e6b6c0957edb1311028a49a35e76 | NA | NA | NA | NA | NA | NA
142 | survival | 3.2-7 | Repository | CRAN | 39c4ac6d22dad33db0ee37b40810ea12 | NA | NA | NA | NA | NA | NA
143 | sys | 3.4 | Repository | CRAN | b227d13e29222b4574486cfcbde077fa | NA | NA | NA | NA | NA | NA
144 | systemfonts | 0.3.2 | Repository | CRAN | 046e821d454edb3722192f588f4d7884 | NA | NA | NA | NA | NA | NA
145 | testthat | 3.0.0 | Repository | CRAN | 13298cedd051cb7b8a8972d380b559a6 | NA | NA | NA | NA | NA | NA
146 | textshaping | 0.2.1 | Repository | CRAN | a34d4aa94ca91a52710b1c0c36bcded6 | NA | NA | NA | NA | NA | NA
147 | tibble | 3.0.4 | Repository | CRAN | 71dffd8544691c520dd8e41ed2d7e070 | NA | NA | NA | NA | NA | NA
148 | tidyr | 1.1.2 | Repository | CRAN | c40b2d5824d829190f4b825f4496dfae | NA | NA | NA | NA | NA | NA
149 | tidyselect | 1.1.0 | Repository | CRAN | 6ea435c354e8448819627cf686f66e0a | NA | NA | NA | NA | NA | NA
150 | tidyverse | 1.3.0 | Repository | CRAN | bd51be662f359fa99021f3d51e911490 | NA | NA | NA | NA | NA | NA
151 | tinytex | 0.27 | Repository | CRAN | 264b4a31d35bb6833566a7763356ab63 | NA | NA | NA | NA | NA | NA
152 | usethis | 1.6.3 | Repository | CRAN | c541a7aed5f7fb3b487406bf92842e34 | NA | NA | NA | NA | NA | NA
153 | utf8 | 1.1.4 | Repository | CRAN | 4a5081acfb7b81a572e4384a7aaf2af1 | NA | NA | NA | NA | NA | NA
154 | vctrs | 0.3.5 | Repository | CRAN | d25c5bea636cf892edbfd64fc3d20c20 | NA | NA | NA | NA | NA | NA
155 | viridisLite | 0.3.0 | Repository | CRAN | ce4f6271baa94776db692f1cb2055bee | NA | NA | NA | NA | NA | NA
156 | waldo | 0.2.3 | Repository | CRAN | 181d1a31b1ba2009ef20926f2ee0570c | NA | NA | NA | NA | NA | NA
157 | webdriver | 1.0.5 | Repository | CRAN | 966f2cee50cf95fdbce9c395187b2baf | NA | NA | NA | NA | NA | NA
158 | webshot | 0.5.2 | Repository | CRAN | e99d80ad34457a4853674e89d5e806de | NA | NA | NA | NA | NA | NA
159 | whisker | 0.4 | Repository | CRAN | ca970b96d894e90397ed20637a0c1bbe | NA | NA | NA | NA | NA | NA
160 | withr | 2.3.0 | Repository | CRAN | 7307d79f58d1885b38c4f4f1a8cb19dd | NA | NA | NA | NA | NA | NA
161 | xfun | 0.19 | Repository | CRAN | a42372606cb76f34da9d090326e9f955 | NA | NA | NA | NA | NA | NA
162 | xml2 | 1.3.2 | Repository | CRAN | d4d71a75dd3ea9eb5fa28cc21f9585e2 | NA | NA | NA | NA | NA | NA
163 | xopen | 1.0.0 | Repository | CRAN | 6c85f015dee9cc7710ddd20f86881f58 | NA | NA | NA | NA | NA | NA
164 | xtable | 1.8-4 | Repository | CRAN | b8acdf8af494d9ec19ccb2481a9b11c2 | NA | NA | NA | NA | NA | NA
165 | yaml | 2.2.1 | Repository | CRAN | 2826c5d9efb0a88f657c7a679c7106db | NA | NA | NA | NA | NA | NA

**Comment by jwildfire** [comment]
@xni7 Looks good - Glad it ran smoothly! Would you mind merging the updates from Renan that just went in to `module-renderer` and then doing a PR?

**Comment by jwildfire** [comment]
Also - do we to update our development workflow at all to keep {renv} happy and up to date? The [intro](https://rstudio.github.io/renv/#workflow) makes it seem like everything is automated after the initial set up - is that correct?

**Comment by jwildfire** [comment]
After further discussion, we're not going to pursue renv for v2, though we may revisit later. Closing this for now.
