### ISSUE TITLE
Add missing dependencies

### ISSUE THREAD

**Issue by rescalan** [SafetyGraphics/safetyGraphics#450]
I noticed that the following dependencies needed to be installed in order to run safetyGraphics {esquisse}, {Tendril}, {Tplyr}, {kableExtra} however they are not listed in DESCRIPTION. I will add them in a PR.

**Comment by jwildfire** [comment]
Thanks for the issue/PR! 

{Tplyr} and {kableExtra} are all actually called in {safetyCharts}, so I've filed [an issue there](https://github.com/SafetyGraphics/safetyCharts/issues/30). Will accept the PR to add {esquisse} shortly.
