### ISSUE TITLE
Improve documentation regarding RS Connect/Shiny Server deploy

### ISSUE THREAD

**Issue by elimillera** [SafetyGraphics/safetyGraphics#457]
Hey @jwildfire,

Fantastic package. I had wanted to deploy this to an RS Connect server but there were a couple of things seem to block that.

Here are the list of steps to deploy to RS Connect so far:

1. Move 'SafteyGraphicsApp.R' to the top level directory and rename 'App.R'
2. Change the final line of `safetyGraphicsApp()` to `shiny::shinyAppDir()`. This is what it takes RStudio to understand this is deployable.
3. The process of deploying doesn't put some things in the environment. I renamed the file 'data/chartsMetadata.Rda' to 'data/chartsMetadata.Rds' and changed the safetygraphicsApp to point at it.
4. Similar process with 'adlbc.rda'.
5. 'inst/' was prepended to a few places where things weren't in the top level.

I'm still getting an error at this point with 'settingsMetadata' but the stacktrace isn't being very helpful. Once I have this figured out hopefully I'll have a connect deployment that people can review.

**Comment by jwildfire** [comment]
Thanks for the issue, @elimillera. I'm going to play with this on our RS connect instance over the next few weeks and see how things go. Definitely think there is some room for improvement here ... 

What branch are you deploying now? `dev` or `module-renderer`? Planning to merge those ASAP, btw.

**Comment by samussiah** [comment]
I'm having trouble deploying as well but not getting near as far as @elimillera did.  I'm hitting an `rlang` version discrepancy.  I'll go ahead and reference this issue in a discussion.

**Comment by jwildfire** [comment]
@elimillera @samussiah - I think the improved modularization of the app should help with this ... Does the approach documented [here](https://github.com/SafetyGraphics/safetyGraphics/wiki/Vignette:-Data-pipelines-and-Security-FAQ#q-can-i-deploy-safetygraphics-to-an-internal-rsconnect-server) work for you? Any other details we should add to that FAQ?

**Comment by samussiah** [comment]
Thanks @jwildfire .  The deployment can't find safetyGraphics v2.0.0.  The ShinyApps.io documentation says it'll look to GitHub but it seems to only be looking at https://cran.rstudio.org.

**Comment by samussiah** [comment]
Got it working by installing locally in the Shiny App directory:
```
library(safetyGraphics, lib.loc = 'library')
```

**Comment by elimillera** [comment]
Hey @jwildfire @samussiah I was also able to deploy to connect after a couple of changes. I'll add those in as a PR so we can go over what changed.
Thanks!
