### ISSUE TITLE
safetyOutlierExplorer and safetyResultsOverTime widgets initialization

### ISSUE THREAD

**Issue by xni7** [SafetyGraphics/safetyGraphics#465]
@jwildfire , I tried an ADaM dataset with AVISIT and AVISITN columns, but couldn't render safetyOutlierExplorer or safetyResultsOverTime widgets. ` The value "VISIT" for the this.config.x.column setting does not match any column in the provided dataset.`

After referring to their JS Data Guidelines, two widgets requires other metadata/mapping than `visit_col` and `visitn_col`. 

- [outlier widget: `time_cols`](https://github.com/RhoInc/safety-outlier-explorer/wiki/Data-Guidelines#data-specification)
- [boxplot widget: `time_settings`](https://github.com/RhoInc/safety-results-over-time/wiki/Data-Guidelines)

Two considerations

- Add a test for ADaM data with `AVISIT` and `AVISITN` only, e.g. [tests/testthat/module_examples/chartsRenderWidget/app.R](https://github.com/SafetyGraphics/safetyGraphics/blob/dev/tests/testthat/module_examples/chartsRenderWidget/app.R). I added a safetyOutlierExplorer widget and additional mapping and got it rendered.

```r
mappingLabs$time_cols <- data.frame(
  value_col = c("AVISIT", "ADY"),
  type = c("ordinal", "linear"),
  order_col = c("AVISITN" , "null"),
  rotate_tick_labels = c(T,F),
  vertical_space = c(100,0)
)
```
-  Add widget init function in config/workflow. The [Chart Config Vignette](https://github.com/SafetyGraphics/safetyGraphics/wiki/Chart-Configuration-Vignette-(v2)#example-3---htmlwidgets-and-init-functions) is really helpful! I followed the [aeExplorer_init()](https://github.com/SafetyGraphics/safetyCharts/blob/dev/inst/config/workflow/aeExplorer_init.R) example and created a custom workflow for safetyOutlierExplorer_init() function and added to its YAML. It worked like a charm!

```r
safetyOutlierExplorer_init<- function(data, settings){
    print(data)
    print(settings)
    
    settings$time_cols <- data_frame(
        value_col = c(settings[["visit_col"]], settings[["studyday_col"]]),
        type = c("ordinal", "linear"),
        order_col = c(settings[["visitn_col"]] , "null"),
        rotate_tick_labels = c(T,F),
        vertical_space = c(100,0)
    )
    
    return(list(data=data,settings=settings))
}
```

Comments

- I think the widget initialization is "hidden" in the code backend, and users need to familiar with the JavaScript Data Specifications. It will be challenging for non technical users. 
- Some of the widget JS settings are not in the meta data, perhaps consider some chart specific control UIs using Shiny on those charts?

**Comment by xni7** [comment]
Can also rename AVISIT/AVISITN to VISIT/VISITNUM and use the default settings

**Comment by jwildfire** [comment]
Nice write-up, @xni7! I'm *really* glad you could work through this bug the init function and test infrastructure. Moving forward, I think your last comment is the most straightforward way to fix the issue. 

> Can also rename AVISIT/AVISITN to VISIT/VISITNUM and use the default settings, or add more widgets settings to the meta data table?

Yes! I'll put in a quick PR that updates `meta` with the correct Adam column names, and hopefully that will fix things for this use case.

**Comment by jwildfire** [comment]
> * I think the widget initialization is "hidden" in the code backend, and users need to familiar with the JavaScript Data Specifications. It will be challenging for non technical users.
> * Some of the widget JS settings are not in the meta data, perhaps consider some chart specific control UIs using Shiny on those charts?

Yeah, I hear you. I do think that building shiny module "wrappers" that allow for additional customization of some of the more complex widgets is a good option down the road. Also no reason we can't create some `{safetyexploreR}` style wrapper functions with more robust parameterization in `{safetyCharts}` down the road. 

My plan was wait and see what users ask for before putting in too much work on this front, but certainly open to discussion.

**Comment by jwildfire** [comment]
@xni7 I also would've thought you could just update the columns in the mapping tab ... was that not working as expected?
