### ISSUE TITLE
Coerce factors to strings, specifically for measure column.

### ISSUE THREAD

**Issue by samussiah** [SafetyGraphics/safetyGraphics#476]
Otherwise the measure value dropdowns populate with the factor index, which wasn't immediately apparent.  Alternatively warn the user to coerce categorical columns to character.

**Comment by jwildfire** [comment]
Thanks for the issue @samussiah. Assuming you ran this on `master`? I'll check and see if this is still happening on the `dev` branch where we're working on v2.

**Comment by samussiah** [comment]
Yep, v1.1 off CRAN.

**Comment by jwildfire** [comment]
This is mostly working in newest build, so I think I am going to close this. hep-explorer seems to be the one renderer that doesn't like factors now, so I'll just file an issue in safetyCharts. 

```
devtools::load_all()
domainData<-list(
    labs=safetyData::adam_adlbc, 
    aes=safetyData::adam_adae, 
    dm=safetyData::adam_adsl
)
domainData$labs$PARAM <- factor(domainData$labs$PARAM )
safetyGraphicsApp(domainData=domainData)
```

**Comment by jwildfire** [comment]
@samussiah - feel free to test a bit more and re-open if you see more problems.
