### ISSUE TITLE
Update copyright holder

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#497]

**Comment by jwildfire** [comment]
I'm going to add  `person("Interactive Safety Graphics Working Group", role = "cph")`  to list the working group as the copyright holder unless someone has a better idea ...

@xni7 @JimBuchanan @mli1 @elimillera: thoughts?

**Comment by JimBuchanan** [comment]
Sounds reasonable to me.

Thanks,

Jim
