### ISSUE TITLE
Clean up `inst`

### ISSUE THREAD

**Issue by samussiah** [SafetyGraphics/safetyGraphics#506]
The `htmlwidgets` collection has been moved to `safetyCharts` so it's no longer needed in `safetyGrahpics` right?  Is part of the UI `htmlwidgets`-driven?

**Comment by jwildfire** [comment]
Yeah, we need to do this (and delete various other orphaned files) before v2 goes out the door.

**Comment by jwildfire** [comment]
Expanding scope a bit to clean up all of /inst.
