### ISSUE TITLE
Allow chart import from packages

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#531]
Per recent discussions with @elimillera, we want to let external packages natively include safetyGraphics charts. I'm thinking we should support adding charts from external packages stored in their `inst/safetyGraphics` folder. Then we can add a `packages` parameter to `makeChartConfig` that looks in that location. Note that this isn't too different from the current process used to load charts from `safetyCharts`, so I really don't think it will require major code updates. 

In short, when the `packages` parameter is provided, `makeChartConfig` would do the following for each package listed: 

1) Search the user's libpath to confirm that the package is installed. Throw a warning if it's not. 
2) Look for YAML configuration files (and any associated R functions) in a pre-specified location - I'm thinking `/inst/safetyGraphics`
3) Add any charts found to the chart object. 

This update would allow us to move away from the (slightly obscure) way we are defaulting to `safetyCharts`. Instead of using it as a hard-coded fallback when no directories are provided, we can just set it as the default value for the new `packages` parameter. This should also allow us to more easily load packages from multiple sources by providing both file paths and package names if desired. 

Also thinking we should allow users to pass existing chart objects to this function so that users could easily add new chart(s) on to an existing instance of safetyGraphics, without having to regenerate the other chart objects. This might be a bit more complex, so may bump it to a separate issue ... 

@elimillera @xni7 How does this sound?

**Comment by xni7** [comment]
@jwildfire , sounds like a reasonable workflow! We need to consider the impact on the project initiation and RStudio add-in workflows.
