### ISSUE TITLE
Can't load sas7bdat in `safetyGraphicsInit()`

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#568]
See notes in [this PR](https://github.com/SafetyGraphics/safetyGraphics/pull/564). @xni7 to confirm fix deployed in `jwildfire/datamods` fixes the problem.

**Comment by xni7** [comment]
Issue persisted for me.  See my note https://github.com/SafetyGraphics/safetyGraphics/pull/564#issuecomment-852294779

**Comment by jwildfire** [comment]
Thanks @xni7. Will look a bit more shortly.

**Comment by jwildfire** [comment]
OK - I think I've fixed it in `jwildfire/datamods`. @xni7 - can you give it another run to confirm?

**Comment by jwildfire** [comment]
Excellent. Filed https://github.com/dreamRs/datamods/issues/24. We can close this once that is resolved.

**Comment by jwildfire** [comment]
Issue is resolved over in the datamods github repo, so SAS files will load fine if you use `install_github(dreamRs/datamods)` to install the package. Will leave this open until the next CRAN release.

**Comment by jwildfire** [comment]
Fixed in datamods v1.1.5
