### ISSUE TITLE
Filter out early AE on demo shiny.io site

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#573]
Make some minor data tweaks in the demo data including removing the AE from day -5000 so that the AE timeline looks a bit better. 

@xni7 Do you think the lab data needs updates also?

**Comment by xni7** [comment]
Done, filtered the AE timeline plot in demo app. The lab data are good, no need to filter. 
![image](https://user-images.githubusercontent.com/31833867/121784897-b81d9480-cb84-11eb-894d-9dc1b580da63.png)

**Comment by jwildfire** [comment]
Thanks @xni7. Looks much better. Closing this issue.
