### ISSUE TITLE
hep-explorer won't renderer 

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#575]
Hep explorer not rendering for most users. @xni7 discovered that this was related to a capitalization issue. 

@xni7 any code changes needed for this? do we need to make an update the the YAML file in safetyCharts?

**Comment by xni7** [comment]
@jwildfire all changes are here https://github.com/SafetyGraphics/safetyCharts/commit/3258c27a0f5f19ec67bef18544bb7adeb50da78e. I can do a PR there?

**Comment by jwildfire** [comment]
That'd be great @xni7. I created https://github.com/SafetyGraphics/safetyCharts/issues/62 over in safetyCharts and assigned you. Closing this for now, since no updates needed in safetyGraphics.
