### ISSUE TITLE
Developmental versions of dependencies cause errors

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#583]
From @xni7 in #581. When using `devtools::install_github("safetyGraphics/safetyCharts", ref="update-configs")`  RStudio IDE prompted updating R packages including Shiny and bslib to latest on github. The developmental version broke the app
 
```
bslib            0.2.5.9002  2021-06-15 [1] Github (rstudio/bslib@2a6e62d)  
shiny          * 1.6.0.9021  2021-06-15 [1] Github (rstudio/shiny@b3247d5)
```
See err msg. Downgrading to Shiny 1.6.0 on CRAN made the err go away. Perhaps in the vignette we instruct users to update CRAN pkgs only? 
```
Warning: Error in : 'tab_append' is not an exported object from 'namespace:bslib'
  55: %>%
  54: module
  49: callModule
  48: server
Error : 'tab_append' is not an exported object from 'namespace:bslib'
In addition: Warning messages:
1: package ‘dplyr’ was built under R version 4.0.4 
2: Navigation containers expect a collection of `bslib::nav()`/`shiny::tabPanel()`s and/or `bslib::nav_menu()`/`shiny::navbarMenu()`s. Consider using `header` or `footer` if you wish to place content above (or below) every panel's contents.
```

**Comment by jwildfire** [comment]
Not sure how much to worry about this. Does `install_github()` always try to install developmental builds?

**Comment by jwildfire** [comment]
@xni7 Are you still getting this issue? I'm not quite sure how to re-produce and debug ... thoughts?

**Comment by xni7** [comment]
@jwildfire Haven't seen these errors lately, and no one else has reported. I think let's just close for now and reopen later if needed.
