### ISSUE TITLE
Typos in Vignettes

### ISSUE THREAD

**Issue by waterhob** [SafetyGraphics/safetyGraphics#639]
@jwildfire Here are the location of the typos I noticed while reading through the Vignettes

# Typos in Intro
1. "in to" should be "into" in the text block below:
>**Passing data to safetyGraphicsApp()**
>You can also initialize the app with custom data directly from the R console. The basic workflow is as follows:

>1. Load your data **in to** the R session

2. "so" should be "to" in the text block below:
> **Appendix 2 - Minimum Data Requirements**
>Since the safetyGraphics framework supports adding custom charts (that may have custom settings), there are no universal data requirements for the app. However, the charts included by default version of the app are built **so** share requirements whenever possible.

# Typos in Chart Configuration Vignette
1. Under **Example 3** there is a space before a ! that should be there in the text block below:
>Next we define a server function that populates the control for selecting measurements and then draws the plot using safetyCharts::safety_outlier_explorer() charting function - which is based on the spaghetti() function **!**

# Technical FAQ Vignette
1. "in to" should be "into" in the text block below:
> **Q**: Is the safetyGraphics package validated?
**A**: As of the version 2 release, the safetyGraphics package is intended for exploratory use only and is not validated or qualified per 21 CFR Part 11. No warranty or guarantees are included as part of the package. Further, any formal validation should be fit for purpose and follow your organization's procedures. That said, extensive quality checks are built in to the package (see the question below for details) and **in to** many of charts that are included by default.

2. Missing "." between "vignette" and "safetyGraphics" below"
> **Q**: What data sources does safetyGraphics support? How do I load custom data?
**A**: This topic is covered in detail in the Loading data section of the Introductory **vignette** **safetyGraphics** is designed to support

3. In the same Q/A there is a repeated "the"
> In short, data can be loaded using **the the** dataDomains parameter in the safetyGraphicsApp() function or via the safetyGraphicsInit() graphical user interface.

4. There is an unneccessary "a" in the block below:
> **Q**: How can the safetyGraphics app be shared?
**A**: The safetyGraphics app can be shared using standard shiny methodology. More details for **a** specific use cases are given in the next few questions.

5. I recommend changing the highlighted "in" to "for"
> **Q**: How do I avoid R not choking on the huge volume of lab data? 
**A**: This is a very good question, and in my experience the answer is complex and varies for different use cases. Focusing on specific toxicities helps, but probably isn't enough **in** really big studies. 

6. In the same question for the last sentence you are missing a "." at the end, and the word "on" between "are" and "our"
> Fortunately this is all doable in R, and improvements in this area **are our** radar for safetyGraphics after v2 goes live

**Comment by jwildfire** [comment]
Thanks very much @waterhob. This is just perfect. 

I've updated the wiki and will leave this issue open as a reminder to update the vignettes in the R package next time we push to CRAN. Thanks again for the close read!
