### ISSUE TITLE
Add more general info regarding data security to FAQ 

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#645]
Would like to find a link that says: "When you run a shiny app using RStudio on your local machine, no data leaves your computer." I know there are caveats to that, but it would be good to find a link that spells all that out in detail. The following 2 links are worth including, but not sure it directly addresses the comment above.  

- https://mastering-shiny.org/scaling-security.html#data
- https://support.rstudio.com/hc/en-us/articles/360042593974-R-and-R-Package-Security

**Comment by jwildfire** [comment]
Other notes from email that we could include ... 
- I can see that the software has the MIT license, so does this essentially mean that any company would be free to use the software without restriction?
   - Yep - package is open source and free to use.  
- With regards to the dedicated server, in my opinion this would only be necessary if a lot of people were using the software in R at the same time, but perhaps you have a different perspective having used the software a lot more than me? ​
    - I generally agree, but it depends a bit on your use-case. If analysts are just using the data in an exploratory fashion, they can probably just run the app from RStudio, but if you're using the app for medical monitoring in active studies, you probably need a more robust set up. There's some discussion of this in the FAQ.  
- Maybe there is also some data security aspect to consider, but this is something I know nothing about!  
    - The short answer is that you should probably check with IT to be safe, but this deserves more discussion in the FAQ - I'll put something together and send you a note when it's ready.

**Comment by xni7** [comment]
look good! The 2nd paragraph is spot on. The data security considerations depend on where the app is deployed, where the data are loading from, and where the data are uploaded to.  Not sure if HIPAA and patient private info protection is a concern/consideration. 

https://www.hhs.gov/ohrp/sites/default/files/report-privacy-and-health-10-31-19.pdf
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4943495/
https://www.d-wise.com/blog/detailing-the-de-identification-and-data-transparency-boundaries-of-ema-policy-70-and-gdpr

**Comment by jwildfire** [comment]
Added several new questions to the FAQ based on the discussion above. Thanks for the links @xni7 and @elimillera
