### ISSUE TITLE
Color indication for treatment group, sex, age, Race in Hepatic safety explorer

### ISSUE THREAD

**Issue by martingebel** [SafetyGraphics/safetyGraphics#662]
What do I have to do to get the color coding for the variables mentioned above?

Currently, in contrast to the help pdf file, the Group tab does not appear when I start the Hepatic safety explorer.
Although, I have added the variables with same names set as variables for DM (TRT01A,SEX,AGEGRP1).

I aslo I tried the variable names used in the pdf (AGEGP1 TRTA), but this did not work either
![error](https://user-images.githubusercontent.com/91063474/157495527-5b7e9e04-1300-4261-b0e7-26d98f9a53ec.PNG)
.

**Comment by jwildfire** [comment]
> What do I have to do to get the color coding for the variables mentioned above?

I don't think adding the grouping in the Shiny app is supported in the current build. This is a consequence of splitting the data up in to multiple data domains in v2.0. 

I'll write up notes on a work around later (you can initialize the hepatic explorer directly from the R command prompt), and will think about the best way to implement in the shiny app in an upcoming release.

**Comment by jwildfire** [comment]
@martingebel We're testing out a new function that allows for easier customization of the hepatic explorer (and eventually other widgets) over in safetyCharts. Here's some demo code. 

```
devtools::install_github('safetyGraphics/safetyCharts', ref='dev')

?hepExplorer 

# Render widget with defaults
hepExplorer() 

# Add age group to default
hepExplorer(group_cols=c("SEX","AGEGR1")) 

# Enable interactive y-axis
hepExplorer(y_options='all') 

# Use custom mapping for SDTM data
hepExplorer(
    df=safetyData::sdtm_lb,
    measure_col = "LBTEST", 
    measure_values = list(
        ALT = "Alanine Aminotransferase", 
        AST = "Aspartate Aminotransferase", 
        TB = "Bilirubin",
        ALP = "Alkaline Phosphatase"
    ), 
    id_col = "USUBJID", 
    value_col = "LBSTRESN", 
    normal_col_low = "LBORNRLO",               
    normal_col_high = "LBORNRHI", 
    studyday_col = "LBDY", 
    visit_col = "VISIT",
    visitn_col = "VISITNUM"
)
```

Thoughts and feedback welcome. Should be heading to CRAN in the next week or 2.

**Comment by jwildfire** [comment]
Going to go ahead and close this issue. Will update https://github.com/SafetyGraphics/safetyCharts/issues/99 when we add support for grouping columns in the shiny app.
