### ISSUE TITLE
Run application failed after importing data frames 

### ISSUE THREAD

**Issue by ningxuca** [SafetyGraphics/safetyGraphics#684]
Hi, I run safetyGraphicsInit and imported the ae, dm and lb data frames and clicked run application, warning messages popped up in RStudio. I also tried SafetyData's datasets. The same error message. I have the R version 4.2 and RStudio 2022.02.3 
![Screenshot 2022-06-14 215116](https://user-images.githubusercontent.com/106090568/173739294-3d1ea78a-951e-4476-a948-2d47943eb1ae.png)

**Comment by jwildfire** [comment]
Hi @ningxuca - Can you try running increasing the `delayTime` option to see if that helps? Default is 1000 (1 second), so you could try `safetyGraphicsInit(delayTime=3000)` (or even higher)

**Comment by ningxuca** [comment]
yes, it worked. Greatly appreciated, Jeremy!
