### ISSUE TITLE
Object 'ARM' not found when it's a column in ADAE

### ISSUE THREAD

**Issue by ningxuca** [SafetyGraphics/safetyGraphics#687]
ADAE has ARM column, but I got an error message for **Chart Tendril Plot  Type plot  Data Domai
![Screenshot 2022-06-16 155735](https://user-images.githubusercontent.com/106090568/174191778-22152fe7-0af2-48d4-96bb-cf2128ad9e54.png)
n aes dm  Links tendril**

**Comment by jwildfire** [comment]
Hi @ningxuca - It's not very obvious in the app, but the expectation is for ARM to be in the `dm` data set (typically `adsl` if you're using ADaM). You could customize the chart to pull ARM from AE, but would take a bit of work. 

The upcoming v2.2 release will make this a bit easier to figure out directly in the app.

**Comment by ningxuca** [comment]
Hi Jeremy,

I have ARM in ADSL (DM) as well. It didn't work so that I put it in ADAE
(aes) as well. ARM in both places.

Thanks,

Emily
