### ISSUE TITLE
example in the cookbook didn't work. Function read_yaml NOT found

### ISSUE THREAD

**Issue by ningxuca** [SafetyGraphics/safetyGraphics#688]
qtOutliers<-prepareChart(read_yaml('https://raw.githubusercontent.com/SafetyGraphics/safetyCharts/dev/inst/config/safetyOutlierExplorer.yaml') )
![Screenshot 2022-06-16 160151](https://user-images.githubusercontent.com/106090568/174192121-06d4962f-fc56-407f-ac38-c0e8131c6ab7.png)

Error in read_yaml("https://raw.githubusercontent.com/SafetyGraphics/safetyCharts/dev/inst/config/safetyOutlierExplorer.yaml") : 
  could not find function "read_yaml"

**Comment by jwildfire** [comment]
Thanks for the note @ningxuca. You can install the `yaml` package before running the example by calling this code:

```
install.packages('yaml')
library('yaml')
```

I'll add that code to the vignette before the next release.
