### ISSUE TITLE
Update Settings Handling in eDish widget

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#69]
`settings` parameter should serve as the default, with any specified parameters (e.g. `id_col`) overwring the default values from the settings object. 

Of you specify `settings = list(id_col="USUBJID", measure_col="MEASURES", ...)` and `id_col="ID"`, the final settings passed to the chart should be list(id_col="ID", measure_col="MEASURES", ...)

**Comment by bzkrouse** [comment]
Decided to change approach to widget-specific settings (#266).  
In #199, we implemented the ability to specify custom settings on top of default settings.
