### ISSUE TITLE
Allow user to configure permanent settings for use across multiple R sessions

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#73]
Use case is that a certain user or set of users has an internal data standard that they always want to serve as the default data mapping for the chart .

**Comment by jwildfire** [comment]
Would be nice to document this process in a vignette or wiki page. Good candidate for v1.1.

**Comment by bzkrouse** [comment]
Could see a couple ways of doing this:
- export settings as file (#337)
- bookmark state

**Comment by pburnsdata** [comment]
Based on meeting, add setting to safetyGraphicsApp() that allows you to point to alternative locations to load settings and metadata. This will allow users to set up their own chart selections and settings etc. and reuse them. Simple example would be to take the current metadata, remove a few charts, place them in another location, and then point there. Sound good @jwildfire ?

**Comment by jwildfire** [comment]
Closing as duplicate of #356
